### PR TITLE
Update npm-registry-client to 7.1.0

### PR DESCRIPTION
**Pull request by NicolasPetton**
This updates fixes the build of `node-packages-generated.nix`, and addresses #35 as well.

/cc @shlevy @offlinehacker

### CODE REVIEW

**Comment by shlevy** [comment]
LGTM, though IIRC there's some way for packages to specify deps in other registries? Would be nice if we could respect that.

**Comment by DamienCassou** [comment]
@shlevy does it make sense to merge this PR now and to improve npm2nix with what you propose in another PR?

**Comment by offlinehacker** [comment]
Support for scoped packages still has to be added to nix side.

**Comment by NicolasPetton** [comment]
@shlevy @DamienCassou I'd go for merging this one, as it fixes building node-packages-generated.nix, and add support for other registries in another PR.

**Comment by NicolasPetton** [comment]
@shlevy @DamienCassou Any news regarding the PR? We cannot rebuild `node-packages-generated.nix` until then.

**Comment by DamienCassou** [comment]
To me it looks ok, but I can't merge it because I'm not a maintainer of npm2nix.

**Comment by shlevy** [comment]
It seems @garbas, @rbvermaa and @svanderburg are.

**Comment by garbas** [comment]
@NicolasPetton tnx!

**Pull request closed without merging**
